language: python
env:
  global:
    - PYTHONIOENCODING='utf-8'
matrix:
  include:
  - python: "2.7"
    env: PACKAGES='pyev git+https://github.com/dex4er/Pyjo'
  - python: "3.4"
    env: PACKAGES='pyev git+https://github.com/dex4er/Pyjo'
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install bzr devscripts dh-autoreconf
  - bzr branch lp:ubuntu/libev
  - cd livev && debuild -b -us -uc && sudo debi
  - # pip install -q flake8
  - # flake8 --config .flake8 .
  - if [ -n "$PACKAGES" ]; then pip install $PACKAGES; fi
script:
  - python test.py
