sudo: required
dist: trusty
language: python
addons:
  apt:
    packages:
    - libev-dev
matrix:
  include:
  - python: "2.7"
    env: PYTHONIOENCODING='utf-8'
  - python: "2.7"
    env: PYTHONIOENCODING=''
  - python: "3.4"
    env: PYTHONIOENCODING='utf-8'
  - python: "3.4"
    env: PYTHONIOENCODING=''
  - python: "3.5"
    env: PYTHONIOENCODING='utf-8'
  - python: "3.5"
    env: PYTHONIOENCODING=''
  - python: "pypy"
    env: PYTHONIOENCODING='utf-8'
script:
  - python test.py
